### PR TITLE
Use GitHub Actions instead of TravisCI

### PR DESCRIPTION
**Pull request by farodin91**
Signed-off-by: farodin91 <farodin91@googlemail.com>

### CODE REVIEW

**Comment by farodin91** [comment]
@FlorianHockmann Do you like to set nuget key?

**Comment by farodin91** [comment]
@FlorianHockmann You can set a env under: https://github.com/JanusGraph/janusgraph-dotnet/settings/secrets/actions

**Review by FlorianHockmann — APPROVED** [review]
LGTM and I've also added the `NUGET_KEY` variable as a _Repository secret_.

**Comment by FlorianHockmann** [comment]
Yeah, the first repo is on GH Actions 🎉

**Pull request merged**
